---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: spring-reachjs-app-1-api
  description: Weather REST API exposed by Spring Boot backend
  tags:
    - rest
    - openapi
    - weather
spec:
  type: openapi
  lifecycle: experimental
  owner: skoussou
  definition:
    $text: https://springboot-route-demo-project.apps.cluster-kq94d.dynamic.redhatworkshops.io/v3/api-docs
